### PR TITLE
Fix loop over targets of all hosts

### PR DESCRIPTION
**Pull request by s-diez**
Hi,

the refactor commit e88b79f contains an error and only iterates over the targets of the first resolved hostname. This can easily be tested with `make run-dev`. I hope the somewhat larger refactoring is fine with you.

### CODE REVIEW

**Comment by s-diez** [comment]
The linter should be fixed now.

**Comment by till** [comment]
@s-diez so the problem was if you add multiple targets, it would only check the first host?

**Comment by s-diez** [comment]
> @s-diez so the problem was if you add multiple targets, it would only check the first host?

Exactly. These are the metrics from `make run-dev`

Current main branch:
```
luzilla_rbls_ips_blacklisted{hostname="smtp.gmail.com",ip="142.250.27.109",rbl="ix.dnsbl.manitu.net"} 0
luzilla_rbls_ips_blacklisted{hostname="smtp.gmail.com",ip="142.250.27.109",rbl="zen.spamhaus.org"} 0
```

With my changes:
```
luzilla_rbls_ips_blacklisted{hostname="mail.gmx.net",ip="212.227.17.168",rbl="ix.dnsbl.manitu.net"} 0
luzilla_rbls_ips_blacklisted{hostname="mail.gmx.net",ip="212.227.17.168",rbl="zen.spamhaus.org"} 0
luzilla_rbls_ips_blacklisted{hostname="mail.gmx.net",ip="212.227.17.190",rbl="ix.dnsbl.manitu.net"} 0
luzilla_rbls_ips_blacklisted{hostname="mail.gmx.net",ip="212.227.17.190",rbl="zen.spamhaus.org"} 0
luzilla_rbls_ips_blacklisted{hostname="mail.messagingengine.com",ip="103.168.172.36",rbl="ix.dnsbl.manitu.net"} 0
luzilla_rbls_ips_blacklisted{hostname="mail.messagingengine.com",ip="103.168.172.36",rbl="zen.spamhaus.org"} 0
luzilla_rbls_ips_blacklisted{hostname="mail.messagingengine.com",ip="103.168.172.51",rbl="ix.dnsbl.manitu.net"} 0
luzilla_rbls_ips_blacklisted{hostname="mail.messagingengine.com",ip="103.168.172.51",rbl="zen.spamhaus.org"} 0
luzilla_rbls_ips_blacklisted{hostname="smtp.fastmail.com",ip="103.168.172.45",rbl="ix.dnsbl.manitu.net"} 0
luzilla_rbls_ips_blacklisted{hostname="smtp.fastmail.com",ip="103.168.172.45",rbl="zen.spamhaus.org"} 0
luzilla_rbls_ips_blacklisted{hostname="smtp.fastmail.com",ip="103.168.172.60",rbl="ix.dnsbl.manitu.net"} 0
luzilla_rbls_ips_blacklisted{hostname="smtp.fastmail.com",ip="103.168.172.60",rbl="zen.spamhaus.org"} 0
luzilla_rbls_ips_blacklisted{hostname="smtp.gmail.com",ip="142.250.27.109",rbl="ix.dnsbl.manitu.net"} 0
luzilla_rbls_ips_blacklisted{hostname="smtp.gmail.com",ip="142.250.27.109",rbl="zen.spamhaus.org"} 0
```

**Comment by till** [comment]
Thank you! 🙏 I see I screwed this up with the refactoring. Do you think we can add an additional test?

**Comment by s-diez** [comment]
> Thank you! 🙏 I see I screwed this up with the refactoring. Do you think we can add an additional test?

Looking into it. Looks like it should be testable.

**Review by till — APPROVED** [review]

**Comment by s-diez** [comment]
@till Thanks for the project and the fast responses

**Pull request merged**
